# Generated by Django 4.2.16 on 2024-11-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('apellido', models.CharField(max_length=150)),
                ('edad', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
